export const SERVICE_KEY = {
  RESTAURANT: {
    GET_RESTAURANTS: 'GET_RESTAURANTS',
    GET_RESTAURANT: 'GET_RESTAURANT',
    POST_RESTAURANT: 'POST_RESTAURANT',
    PUT_RESTAURANT: 'PUT_RESTAURANT',
    DELETE_RESTAURANT: 'DELETE_RESTAURANT',
    RESTAURANT_NAMES: 'RESTAURANT_NAMES',
    RESTAURANT_NAME: 'RESTAURANT_NAME',
  },
  RESTAURANT_REVIEW: {
    GET_RESTAURANT_REVIEWS: 'GET_RESTAURANT_REVIEWS',
    GET_RESTAURANT_REVIEW: 'GET_RESTAURANT_REVIEW',
    POST_RESTAURANT_REVIEW: 'POST_RESTAURANT_REVIEW',
    PUT_RESTAURANT_REVIEW: 'PUT_RESTAURANT_REVIEW',
    DELETE_RESTAURANT_REVIEW: 'DELETE_RESTAURANT_REVIEW',
  },
  REPORT: {
    GET_REPORTS: 'GET_REPORTS',
    POST_REPORT: 'POST_REPORT',
  },
};
